
name: Details

on:
  push:
    branches:  master 
  pull_request:
    branches:  master 

jobs:      
  build:  
     runs-on: ubuntu-latest
     steps: 

    
     - uses: actions/checkout@v2
       name: check out code 
       
     - name: login to ghcr get image
       uses: docker/login-action@v1
       with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN_GITHUB__BP }}
    
     - name: Build images
       uses: docker/build-push-action@v2
       with:
          file: ./Dockerfile
          push: true
          tags: ghcr.io/pungpeee/bookinfo-details:latest
          
  deploy:
    needs: build
    
    runs-on: ubuntu-latest
    steps: 
    - name: Execute ssh command to remote server
      uses: appleboy/ssh-action@master
      with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         script: |
           docker pull ghcr.io/pungpeee/bookinfo-details:latest
           docker run -d -p 8080:8080 --network=bookinfo ghcr.io/pungpeee/bookinfo-details:latest
           
      
